### ISSUE TITLE
Backing stores or RPC aspects?

### ISSUE THREAD

**Issue by joeblew99** [wallix/triplestore#1]
I tried this.

I use the Stanford rdf tool and this library will be super useful.

I can model in protégé and compile with this.

Do you have ideas about what further things you want to add to this ?

Like backing stores or RPC aspects ?

**Comment by fxaguessy** [comment]
Thanks for your feedback.
Note that you can also export from `triplestore` in ntriples (with prefixes and base URL), in order to open it within protégé.

What do you mean by 'backing stores or RPC aspects' ? What are your use cases ? We try to keep this library minimalist and easy to use, but are keen on integrating new use cases.

For now, we plan in our roadmap to (1) add graph traversal algorithms, (2) to be able to compare / make diff of RDF graphs and (3) to export to Turtle.

**Comment by joeblew99** [comment]
Ok so my use case is that i am working with a team of biology researches.
We are mapping biological functional solutions in nature to engineering problems in the world of engineering ( from nano to macro).

So the model is described in protégé so we can work with it.
I can code gen to golang with your package.
Then we suck in the world's biology papers, and machine them to match to the biological ontology and thus engineering solutions 

The machine learning is relatively simple where we need to find synonyms of descriptions using word vectors.
So it's huge amounts of data.
